# Generated by Django 5.1.7 on 2025-03-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textreceiver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textinput',
            name='user_id',
            field=models.CharField(default='default_user', max_length=100),
        ),
    ]
